include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    sized_box_for_whitespace: false
    prefer_single_quotes: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: true
    avoid_function_literals_in_foreach_calls: false
    prefer_function_declarations_over_variables: false
