include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_single_quotes: true
    sized_box_for_whitespace: false
    avoid_function_literals_in_foreach_calls: false
