name: manhuagui_flutter
description: An unofficial application for manhuagui written in flutter

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluttertoast: ^4.0.0
  url_launcher: ^5.7.10
  permission_handler: ^5.0.1+1
  json_annotation: ^3.1.0
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  flutter_ahlib:
    path: 'F:/Projects/flutter_ahlib'
  flutter_web_browser: ^0.13.0
  cached_network_image: ^2.3.3
  flutter_rating_bar: ^3.2.0+1
  photo_view: ^0.10.3
  filesize: ^1.0.4
  shared_preferences: ^0.5.12+4
  material_floating_search_bar: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  retrofit_generator: ^1.4.0+1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
