name: manhuagui_flutter
description: An unofficial application for manhuagui written in flutter

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2 # ^1.0.0
  fluttertoast: ^4.0.0
  url_launcher: ^5.4.7
  permission_handler: ^5.0.0+hotfix.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
