name: manhuagui_flutter
description: An unofficial android application for manhuagui, built in flutter.

publish_to: 'none'
version: 1.2.0
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # basic
  cupertino_icons: ^1.0.5
  logger: ^1.1.0
  fluttertoast: 8.0.7
  url_launcher: ^6.1.5
  permission_handler: ^10.0.0
  flutter_native_splash: 2.1.6
  json_annotation: ^4.6.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  intl: ^0.17.0
  basic_utils: ^5.2.2
  synchronized: ^3.0.0+3
  queue: ^3.1.0+1

  # assists
  flutter_web_browser: ^0.17.1
  flutter_share: ^2.0.0
  wakelock: ^0.6.2
  device_info_plus: 4.0.0
  battery_info: ^1.1.1
  connectivity_plus: 2.3.6+1
  flutter_local_notifications: 9.9.1

  # widgets
  flutter_ahlib:
    path: ../flutter_ahlib
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  photo_view: ^0.14.0
  material_floating_search_bar: ^0.3.7
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  flutter_typeahead: 3.2.7

  # file system & others
  path: 1.8.0
  path_provider: ^2.0.11
  external_path: ^1.0.1
  shared_preferences: ^2.0.15
  event_bus: ^2.0.0
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.3+2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_native_splash:
  color: '#FFFFFF'
  image: lib/assets/splash_logo.png
  branding: lib/assets/splash_copyright.png
  web: false
