/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

// ignore_for_file: constant_identifier_names

// https://www.fluttericon.com/
// https://yqnn.github.io/svg-path-editor/
// https://fonts.google.com/icons?selected=Material+Icons
// https://pictogrammers.com/library/mdi/

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData opened_blank_book = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_both_blank_book = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_left_star_book = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_right_star_book = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_filled_notebook = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_plus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_minus = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_book_cog = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cog = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData application_star_cog = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_menu = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_download = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_sync = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_public = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_book_offline = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_book_replay = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_topmost = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_timeline = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_sync = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_off = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_sync = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_multiple = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_book_clock = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_book_arrow_right = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_global = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth_warning = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_plus = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_minus = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_clock = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_star = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_delete = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_menu = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_book_ascending = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_book_descending = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_concat_right = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_concat_left = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_jpg_move = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_png_move = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_multiple_plus = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_clock = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
