/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

// ignore_for_file: constant_identifier_names

// https://www.fluttericon.com/
// https://yqnn.github.io/svg-path-editor/
// https://fonts.google.com/icons?selected=Material+Icons
// https://pictogrammers.com/library/mdi/

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData opened_blank_book = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_both_blank_book = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_left_star_book = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_right_star_book = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_filled_notebook = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_plus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_minus = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_book_cog = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cog = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData application_star_cog = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
